### ISSUE TITLE
Dar formato a section (sayhi)

### ISSUE THREAD

**Issue by venturamichel** [maitedellano98/soma#2]
- [x] #4
- [x] Revisar los atributos del contenido (font-size, line-height) y los elementos padre de cada elemento anidado de la section (.sayhi) tal como (margin, padding)

**Comment by maitedellano98** [comment]
como llamas al html en el css para el formato de las columnas

**Comment by venturamichel** [comment]
En el html creas el markup:

						 section.caja
                             div.item
                               h2.item__titulo
							   p.item__descripcion
                               img.item__imagen
							div.item
                               h2.item__titulo
							   p.item__descripcion
                               img.item__imagen
							div.item
                               h2.item__titulo
							   p.item__descripcion
                               img.item__imagen

-----

En el css creas el formato:

                        .caja {
                          display: flex; /* crea un layout de cajas flexibles en columnas */
                          /* o puedes conseguir lo mismo con grid */
                          display: grid;
                          grid-auto-flow: column; /* Esta instruccion cambia el flujo default que tiene grid de filas a columnas */
                        }
